//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinco.Infra.Implementation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Sinco.Domain;
    
    public partial class SincoABREntities : DbContext
    {
        public SincoABREntities()
            : base("name=SincoABREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumno { get; set; }
        public virtual DbSet<Det_Registro_Alumno_Materia> Det_Registro_Alumno_Materia { get; set; }
        public virtual DbSet<Materia> Materia { get; set; }
        public virtual DbSet<Profesor> Profesor { get; set; }
        public virtual DbSet<Registro_Alumno_Materia> Registro_Alumno_Materia { get; set; }
        public virtual DbSet<Registro_Profesor_Materia> Registro_Profesor_Materia { get; set; }
    }
}
