//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinco.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Det_Registro_Alumno_Materia
    {
        public int Id { get; set; }
        public int Periodo { get; set; }
        public Nullable<decimal> Nota { get; set; }
        public Nullable<int> Id_Re_Alumno_Materia { get; set; }
    
        public virtual Registro_Alumno_Materia Registro_Alumno_Materia { get; set; }
    }
}
