//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinco.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro_Alumno_Materia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Registro_Alumno_Materia()
        {
            this.Det_Registro_Alumno_Materia = new HashSet<Det_Registro_Alumno_Materia>();
        }
    
        public int Id { get; set; }
        public int Id_Materia { get; set; }
        public Nullable<int> Id_Alumno { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Det_Registro_Alumno_Materia> Det_Registro_Alumno_Materia { get; set; }
        public virtual Materia Materia { get; set; }
    }
}
