//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinco.Domain
{
    using System;
    
    public partial class SPREPORTEALUMNO
    {
        public int ID_REGISTRO { get; set; }
        public string ALUMNO { get; set; }
        public string MATERIA { get; set; }
        public Nullable<decimal> NOTA { get; set; }
        public string PROFESOR { get; set; }
    }
}
