USE [SINCOABR]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE TYPE = 'P' AND NAME = 'SPTRACEEXECUTION') 
	DROP PROCEDURE [DBO].[SPTRACEEXECUTION]  
GO 

CREATE PROCEDURE [DBO].[SPTRACEEXECUTION] 
AS
BEGIN
DECLARE @DBNAME    NVARCHAR(256),
        @PROCNAME  NVARCHAR(256)
SELECT @DBNAME = 'SINCOABR',  
       @PROCNAME = '[DBO].[SPGETNUMBERSPRIME]' 

; WITH BASEDATA AS (
   SELECT QS.STATEMENT_START_OFFSET/2    AS STMT_START,
          QS.STATEMENT_END_OFFSET/2      AS STMT_END,
          EST.ENCRYPTED                  AS ISENCRYPTED, 
		  EST.TEXT                       AS SQLTEXT,
          EPA.VALUE                      AS SET_OPTIONS, 
		  QP.QUERY_PLAN                  AS QUERY_PLAN,    
	      QS.LAST_EXECUTION_TIME         AS LAST_EXECUTION_TIME,
		  EST.OBJECTID                   AS OBJECTID,
          CHARINDEX('<PARAMETERLIST>', QP.QUERY_PLAN) + LEN('<PARAMETERLIST>') AS PARAMSTART,
          CHARINDEX('</PARAMETERLIST>', QP.QUERY_PLAN) AS PARAMEND
   FROM   SYS.DM_EXEC_QUERY_STATS QS
   CROSS  APPLY SYS.DM_EXEC_SQL_TEXT(QS.SQL_HANDLE) EST
   CROSS  APPLY SYS.DM_EXEC_TEXT_QUERY_PLAN(QS.PLAN_HANDLE,
                                            QS.STATEMENT_START_OFFSET,
                                            QS.STATEMENT_END_OFFSET) QP
   CROSS  APPLY SYS.DM_EXEC_PLAN_ATTRIBUTES(QS.PLAN_HANDLE) EPA
   WHERE  EST.OBJECTID  = OBJECT_ID (@PROCNAME)
     AND  EST.DBID      = DB_ID(@DBNAME)
     AND  EPA.ATTRIBUTE = 'SET_OPTIONS'
), NEXT_LEVEL AS (
   SELECT STMT_START, SET_OPTIONS, QUERY_PLAN, LAST_EXECUTION_TIME, OBJECTID,
          CASE WHEN ISENCRYPTED = 1 THEN '-- ENCRYPTED'
               WHEN STMT_START >= 0
               THEN SUBSTRING(SQLTEXT, STMT_START + 1,
                              CASE STMT_END
                                   WHEN 0 THEN DATALENGTH(SQLTEXT)
                                   ELSE STMT_END - STMT_START + 1
                              END)
          END AS STATEMENT,
          CASE WHEN PARAMEND > PARAMSTART
               THEN CAST (SUBSTRING(QUERY_PLAN, PARAMSTART,
                                   PARAMEND - PARAMSTART) AS XML)
          END AS PARAMS
   FROM   BASEDATA
)
SELECT N.OBJECTID AS ID,
	   CR.C.value('@COLUMN', 'NVARCHAR(128)') AS PARAMETRO,
       CR.C.value('@PARAMETERCOMPILEDVALUE', 'NVARCHAR(128)') AS VALOR,
	   N.LAST_EXECUTION_TIME AS FECHA_DE_TRANSACCIÓN
FROM   NEXT_LEVEL N
CROSS  APPLY   N.PARAMS.nodes('COLUMNREFERENCE') AS CR(C)
ORDER  BY PARAMETRO DESC

END
